# 사이트 기본 설정
title: "최진우의 이력서 & 포트폴리오"
name: "최진우"
tagline: "유원대학교 AI 소프트웨어학과 재학생"
email: "your_email@example.com"
description: "꾸준히 배우고 성장하는 개발자 최진우의 개인 홈페이지입니다."

# 사이트 URL (깃허브 페이지 주소)
url: "https://happycat12389.github.io"

# 사이드바 프로필 사진 (images 폴더 안에 넣고 경로 지정)
avatar: "/images/profile.jpg"

# 네비게이션 메뉴 설정
main:
  - title: "이력서"
    url: /cv/
  - title: "포트폴리오"
    url: /portfolio/
  - title: "블로그"
    url: /year-archive/
  - title: "강의 & 발표"
    url: /talks/
  - title: "연락하기"
    url: /about/

# 사이드바 정보
author:
  name: "최진우"
  bio: "유원대학교 AI 소프트웨어학과 재학생 · 꾸준히 배우는 개발자"
  location: "대한민국 서울"
  employer: "학생"
  email: "your_email@example.com"
  github: "happycat12389"
  linkedin: "your-linkedin-id"
  scholar: "your-google-scholar-id"
  orcid: "your-orcid-id"

# 테마 관련 설정
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default # classic, dark, neon 등 변경 가능

# 빌드 설정
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# 소셜 미디어 아이콘 표시
social:
  - title: "GitHub"
    url: "https://github.com/happycat12389"
  - title: "LinkedIn"
    url: "https://linkedin.com/in/your-linkedin-id"
  - title: "이메일"
    url: "mailto:your_email@example.com"

# Google Analytics (추적이 필요 없으면 비워두세요)
google_analytics: ""
